import string


MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 32767
MIN_INGREDIENT_AMOUNT = 1
MAX_INGREDIENT_AMOUNT = 32767
MAX_TAG_NAME_LEN = 32
MAX_TAG_SLUG_LEN = 32
MAX_INGREDIENT_NAME_LEN = 128
MAX_MEASUREMENT_UNIT_LEN = 64
MAX_RECIPE_NAME_LEN = 256
ALPHABET = string.ascii_letters + string.digits
DEFAULT_SHORT_CODE_LENGTH = 6
MAX_SHORT_CODE_LEN = 10
