version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    image: ihulir/foodgram_backend
    env_file:
      - .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: ihulir/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: ihulir/foodgram_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static/
      - media:/media/
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend